# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV

      - run: |
          node -v

      - run: |
          nvm install v10
          node -v
          nvm alias default v10

      - run: |
          node -v

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

orbs:
  heroku: circleci/heroku@x.y # Use the Heroku orb in your config

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git
        requires:
          - build # only run deploy-via-git job if the build job has completed
        filters:
          branches:
            only: master # only run deploy-via-git job on master branch
